### ISSUE TITLE
pgAdmin4 download URL changed

### ISSUE THREAD

**Issue by porkcube** [autopkg/bnpl-recipes#15]
They changed their site slightly so this : 
https://github.com/autopkg/bnpl-recipes/blob/46ab75cbfa560cd318394f145b12099b48f96431/pgAdmin4/pgAdmin4.download.recipe#L26

Should now be : 
`<string>https://www.pgadmin.org/download/pgadmin-4-macos/</string>`

**Comment by barteklk** [comment]
Thanks for noticing.  Download recipe has been updated.
