### ISSUE TITLE
AppCode.munki.recipe - Cannot parse a NULL or zero-length data

### ISSUE THREAD

**Issue by christopherthart** [autopkg/bnpl-recipes#37]
When initiating an AutoPkg run I get the following warning that seems to involve the AppCode.munki.recipe. See the warning message listed below:

WARNING: plist error for /Users/jdoe/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes/JetBrains/AppCode.munki.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Cannot parse a NULL or zero-length data" UserInfo={NSDebugDescription=Cannot parse a NULL or zero-length data}

**Comment by barteklk** [comment]
Thanks for reporting, fixed, closing issue
