### ISSUE TITLE
Riot now Element; download URL has changed

### ISSUE THREAD

**Issue by fseesink** [autopkg/bnpl-recipes#43]
It looks like the Riot.im folks have gone and renamed the client to Element, complete with a brand new website to boot:

https://element.io/

(Last version of Riot.im is v1.6.8.  Latest version of Element is v1.7.5.)

If you then go to the new site, then the download page and hover over the [Mac OS] button, you see the URL to the installer is now

https://packages.riot.im/desktop/install/macos/Element.dmg

hope this helps.

**Comment by barteklk** [comment]
Thanks for reporting.  New recipes now exist for Element.
