### ISSUE TITLE
JetBrains recipes only pulling Intel versions

### ISSUE THREAD

**Issue by patgmac** [autopkg/bnpl-recipes#62]
https://github.com/autopkg/bnpl-recipes/blob/3ebe28d94df38a157ecb2076c27b9b1d75b59d08/JetBrains/JetBrains.download.recipe#L28

JetBrains offers Intel and M1 versions of most/all of their software. The JetBrains recipe is hardcoded to only pull the "Mac" version but if you look at https://data.services.jetbrains.com/products, you'll see there are also "macM1" versions. 

Could we get this as an overridable value added to the recipes?

Note: Although the Intel download appears to be universal, it is not, there are components that are still x86 and results in the users getting a message within the app advising them to download the Apple Silicon version.

**Comment by barteklk** [comment]
Thank you for reporting, fixed in PR #61
