### ISSUE TITLE
supported_architectures for PyCharm is incorrect type

### ISSUE THREAD

**Issue by apizz** [autopkg/bnpl-recipes#66]
You updated the munki recipe to include `supported_architectures`, but you formatted it as a string when this is actually an array of strings: https://github.com/munki/munki/wiki/Supported-Pkginfo-Keys

**Comment by apizz** [comment]
And fwiw, it doesn't matter whether you download the mac or macm1 version of the JetBrains apps (at least DataGrip & PyCharm PE) as regardless you get a universal app version.
<img width="810" alt="Screen Shot 2022-06-27 at 11 41 48 PM" src="https://user-images.githubusercontent.com/11789931/176087186-20622d34-15cc-45c4-9a22-ea0d68af5a80.png">

**Comment by paul-cossey** [comment]
Sorry @apizz that's my bad, I have PR in to fix this https://github.com/autopkg/bnpl-recipes/pull/65 

While the Apps bundles are indeed Universal, there are architecture specific java runtimes included. 

Thanks
Paul

**Comment by barteklk** [comment]
Hi @apizz and thank you for reporting.  As @paul-cossey mentioned, this was fixed by PR #65.
