### ISSUE TITLE
ElementIM recipe failing due to no match on URL (looks like page moved that download recipe points to)

### ISSUE THREAD

**Issue by fseesink** [autopkg/bnpl-recipes#68]
Using ElementIM munki recipe, I noticed it kicked out the following error:
```
No match found on URL: https://element.io/get-started
Failed.
```

Looking in `ElementIM.download.recipe`, I see it points to that URL, which is a page for contacting sales.  I suspect the intended page has moved to `https://element.io/download`.  That page contains links to download the Element client for the different OS, and the HTML code has 2 URLs ending with a `.dmg`.

**Comment by barteklk** [comment]
Thank you for reporting, this is now fixed by #70
