### ISSUE TITLE
PyCharm seems to now be a universal binary instead of ARM vs. Intel

### ISSUE THREAD

**Issue by aysiu** [autopkg/bnpl-recipes#69]
Munki recipe still works if you specify one or the other—it just pulls the universal binary.

**Comment by barteklk** [comment]
Thank you for filing an issue.  From what I can see, there is still a "Select an installer for Intel or Apple Silicon" note on the download page and differentiation between _mac_ and _macM1_ in the JetBrains releases endpoint.  Perhaps a _mac_ (Intel) version was running on _macM1_ (Apple Silicon) through Rosetta?

**Comment by aysiu** [comment]
I checked with some folks in the MacAdmins Slack, and it seems that—even though the binary itself is universal—various supporting parts are Intel-only on Silicon-only.
