### ISSUE TITLE
Error in local.munki.Postman: Processor: URLTextSearcher: Error: No match found on URL

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/bnpl-recipes#9]
Error in local.munki.Postman: Processor: URLTextSearcher: Error: No match found on URL: https://www.getpostman.com/app/download/osx64

**Comment by Daz-wallace** [comment]
Heya,

Is there any update on the pull request for this? Pretty please? 😊

**Comment by crystalllized** [comment]
Please accept his pull, I'm now experiencing this as well

**Comment by barteklk** [comment]
Accepted
